'use strict';
const $=id=>document.getElementById(id), cards=window.CARD_DATA, decks=window.DECK_DATA;
const quantities=new Map();
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function config(){const w=Number($('width').value),h=Number($('height').value),g=Number($('gap').value);if(!Number.isFinite(w+h+g)||w<20||w>190||h<20||h>277||g<2||g>10)throw Error('请设置有效尺寸：宽 20–190、高 20–277、间距 2–10 毫米。');const cols=Math.floor((198+g)/(w+g)),rows=Math.floor((285+g)/(h+g));return{w,h,g,cols,rows,capacity:cols*rows};}
function ordered(){return cards.slice().sort((a,b)=>{const mode=$('sort').value,promoOrder=(a.promo?1:0)-(b.promo?1:0);return (mode==='starsAsc'?a.stars-b.stars||promoOrder:mode==='starsDesc'?b.stars-a.stars||promoOrder:0)||a.code.localeCompare(b.code)||a.rarity.localeCompare(b.rarity)||Number(a.id)-Number(b.id);});}
function filtered(){const q=$('search').value.trim().toLowerCase(),type=$('type').value,rarity=$('rarity').value;return ordered().filter(c=>(!type||c.type===type)&&(!rarity||c.rarity===rarity)&&(!$('selected').checked||quantities.get(c.id))&&[c.code,c.name,c.text].join(' ').toLowerCase().includes(q));}
function list(){return ordered().flatMap(c=>Array.from({length:quantities.get(c.id)||0},()=>c));}
function update(){const n=list().length;$('total').textContent=n;try{const c=config();$('pages').textContent=Math.ceil(n/c.capacity);$('layoutNote').textContent=`A4 纵向 · 每页 ${c.cols} 列 × ${c.rows} 行 · 单面打印`;$('status').textContent='';}catch(e){$('status').textContent=e.message;$('pages').textContent='—';}$('print').disabled=!n;$('preview').disabled=!n;}
function setQuantity(id,n){if(!cards.some(c=>c.id===id)||!Number.isInteger(n)||n<0||n>99)throw Error('每张卡的份数必须是 0–99 的整数。');quantities.set(id,n);update();}
function render(){const visible=filtered();$('libraryCount').textContent=`${cards.length} 个版本 · ${new Set(cards.map(c=>c.code)).size} 个卡号`;$('filteredCount').textContent=`匹配 ${visible.length} 个版本`;$('sourceCount').textContent=`${cards.length} 个版本 / ${new Set(cards.map(c=>c.code)).size} 个不同卡号`;$('gallery').innerHTML=visible.map(c=>`<article class="card ${(quantities.get(c.id)||0)?'chosen':''}" data-id="${escapeHtml(c.id)}"><button class="image-button" data-show="${escapeHtml(c.id)}" aria-label="查看 ${escapeHtml(c.name)} 大图"><img src="${escapeHtml(c.image)}" alt="${escapeHtml(c.name)} ${escapeHtml(c.id)}" loading="lazy"></button><h3>${escapeHtml(c.name)}</h3><div class="rarity-label">${escapeHtml(c.rarity)}</div><div class="card-meta"><span>${escapeHtml(c.code)}</span><span>${c.type==='role'?'角色':'行动'}</span></div><div class="counter"><button data-delta="-1" aria-label="减少 ${escapeHtml(c.id)} 份数">−</button><input type="number" min="0" max="99" value="${quantities.get(c.id)||0}" aria-label="${escapeHtml(c.code)} ${escapeHtml(c.rarity)} 打印份数"><button data-delta="1" aria-label="增加 ${escapeHtml(c.id)} 份数">＋</button></div></article>`).join('')||'<p class="empty">没有匹配的卡牌。</p>';update();}
$('gallery').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.closest('article').dataset.id;if(b.dataset.show){const c=cards.find(c=>c.id===id);$('largeImage').src=c.image;$('largeImage').alt=c.name;$('imageCaption').textContent=c.code+' · '+c.rarity+' · '+c.name;$('lightbox').showModal();return;}const n=Math.max(0,Math.min(99,(quantities.get(id)||0)+Number(b.dataset.delta)));setQuantity(id,n);render();});
$('gallery').addEventListener('change',e=>{if(!e.target.matches('input'))return;try{setQuantity(e.target.closest('article').dataset.id,Number(e.target.value));render();}catch(err){$('status').textContent=err.message;}});
for(const id of ['search','type','selected','rarity','sort'])$(id).addEventListener('input',render);
for(const id of ['width','height','gap','marks'])$(id).addEventListener('input',update);
document.querySelectorAll('[data-deck]').forEach(b=>b.onclick=()=>{const d=decks[b.dataset.deck];quantities.clear();for(const id of d.roles)quantities.set(id,(quantities.get(id)||0)+1);for(const [id,n]of Object.entries(d.actions))quantities.set(id,(quantities.get(id)||0)+n);$('deckNote').textContent='已载入：'+d.name+'（同人网站清单，匹配同卡号最低星级版本）';render();});
$('all').onclick=()=>{cards.forEach(c=>quantities.set(c.id,1));$('deckNote').textContent='已选择全部版本，每个版本 1 份（同卡号可能包含多个星级）。';render();};$('clear').onclick=()=>{quantities.clear();$('deckNote').textContent='已清空选牌。';render();};$('closeImage').onclick=()=>$('lightbox').close();
function buildSheets(){const c=config(),items=list();if(!items.length)throw Error('请先选择卡牌。');const fragment=document.createDocumentFragment();for(let start=0;start<items.length;start+=c.capacity){const sheet=document.createElement('div');sheet.className='sheet';items.slice(start,start+c.capacity).forEach((card,i)=>{const x=(210-(c.cols*c.w+(c.cols-1)*c.g))/2+(i%c.cols)*(c.w+c.g),y=(297-(c.rows*c.h+(c.rows-1)*c.g))/2+Math.floor(i/c.cols)*(c.h+c.g);const slot=document.createElement('div');slot.className='slot';slot.style.cssText=`left:${x}mm;top:${y}mm;width:${c.w}mm;height:${c.h}mm`;const img=document.createElement('img');img.src=card.image;img.alt=card.code+' '+card.rarity;slot.append(img);sheet.append(slot);if($('marks').checked)for(const xx of [x,x+c.w])for(const yy of [y,y+c.h]){for(const horizontal of [true,false]){const mark=document.createElement('i');mark.className='cut';const beforeX=xx===x,beforeY=yy===y;mark.style.cssText=horizontal?`left:${xx+(beforeX?-0.9:0.2)}mm;top:${yy}mm;width:.7mm;height:.1mm`:`left:${xx}mm;top:${yy+(beforeY?-0.9:0.2)}mm;width:.1mm;height:.7mm`;sheet.append(mark);}}});const label=document.createElement('span');label.className='page-label';label.textContent=`${c.w} × ${c.h} mm | 100% | ${Math.floor(start/c.capacity)+1} / ${Math.ceil(items.length/c.capacity)}`;sheet.append(label);fragment.append(sheet);}$('sheets').replaceChildren(fragment);}
async function prepare(){try{buildSheets();$('status').textContent='正在检查预览图片…';await Promise.all([...$('sheets').querySelectorAll('img')].map(img=>img.decode()));$('status').textContent='';$('previewPanel').hidden=false;document.body.classList.add('preview-open');window.scrollTo(0,0);}catch(e){$('status').textContent='无法预览：'+e.message;}}
async function imageAsJpeg(card){let response;try{response=await fetch(new URL(card.image,location.href),{cache:'force-cache'});}catch{throw Error(`无法读取卡图 ${card.code}（${card.rarity}），请刷新页面后重试。`);}if(!response.ok)throw Error(`卡图 ${card.code}（${card.rarity}）加载失败：HTTP ${response.status}`);const objectUrl=URL.createObjectURL(await response.blob());try{const img=new Image();img.src=objectUrl;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0);return canvas.toDataURL('image/jpeg',.94);}finally{URL.revokeObjectURL(objectUrl);}}
function drawCropMarks(pdf,x,y,w,h){pdf.setDrawColor(70);pdf.setLineWidth(.08);const inside=.2,outside=.9;for(const xx of [x,x+w])for(const yy of [y,y+h]){const left=xx===x,top=yy===y;pdf.line(xx+(left?-outside:inside),yy,xx+(left?-inside:outside),yy);pdf.line(xx,yy+(top?-outside:inside),xx,yy+(top?-inside:outside));}}
async function downloadPdf(){const buttons=[$('print'),$('printPreview')];try{const c=config(),items=list();if(!items.length)throw Error('请先选择卡牌。');if(!window.jspdf?.jsPDF)throw Error('PDF 组件未加载，请刷新页面后重试。');buttons.forEach(b=>b.disabled=true);const pages=Math.ceil(items.length/c.capacity),pdf=new window.jspdf.jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true,putOnlyUsedFonts:true});pdf.setProperties({title:'鸣潮对决卡牌打印文件',subject:`${items.length} 张卡牌，${c.w} × ${c.h} mm`});const cache=new Map();for(let i=0;i<items.length;i++){const card=items[i],page=Math.floor(i/c.capacity);if(i&&i%c.capacity===0)pdf.addPage('a4','portrait');const pos=i%c.capacity,x=(210-(c.cols*c.w+(c.cols-1)*c.g))/2+(pos%c.cols)*(c.w+c.g),y=(297-(c.rows*c.h+(c.rows-1)*c.g))/2+Math.floor(pos/c.cols)*(c.h+c.g);let jpeg=cache.get(card.id);if(!jpeg){$('status').textContent=`正在生成彩色 PDF：${i+1} / ${items.length} 张…`;await new Promise(requestAnimationFrame);jpeg=await imageAsJpeg(card);cache.set(card.id,jpeg);}pdf.addImage(jpeg,'JPEG',x,y,c.w,c.h,`card-${card.id}`,'FAST');if($('marks').checked)drawCropMarks(pdf,x,y,c.w,c.h);if(pos===c.capacity-1||i===items.length-1){pdf.setFontSize(7);pdf.setTextColor(90);pdf.text(`${c.w} x ${c.h} mm | 100% | ${page+1} / ${pages}`,10,293);}}$('status').textContent='正在准备下载…';const blob=pdf.output('blob'),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`鸣潮对决_彩色打印_${items.length}张_${new Date().toISOString().slice(0,10)}.pdf`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);$('status').textContent=`已生成 ${pages} 页彩色 PDF，请查看浏览器下载记录。`;}catch(e){$('status').textContent='无法生成 PDF：'+e.message;}finally{buttons.forEach(b=>b.disabled=!list().length);}}
$('preview').onclick=prepare;$('print').onclick=downloadPdf;$('closePreview').onclick=()=>{$('previewPanel').hidden=true;document.body.classList.remove('preview-open');};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_print_quantities',description:'批量设置卡牌打印份数，更新当前打印清单。',inputSchema:{type:'object',properties:{items:{type:'array',items:{type:'object',properties:{id:{type:'string'},quantity:{type:'integer',minimum:0,maximum:99}},required:['id','quantity'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!Array.isArray(input?.items)||input.items.some(x=>!cards.some(c=>c.id===x.id)||!Number.isInteger(x.quantity)||x.quantity<0||x.quantity>99))throw Error('卡号或份数无效');input.items.forEach(x=>quantities.set(x.id,x.quantity));render();return{total:list().length};}})).catch(()=>{});}catch{}}
const rarities=[...new Set(cards.map(c=>c.rarity))].sort((a,b)=>(a.match(/★/g)||[]).length-(b.match(/★/g)||[]).length||a.localeCompare(b));for(const r of rarities){const option=document.createElement('option');option.value=r;option.textContent=r+'（'+cards.filter(c=>c.rarity===r).length+'）';$('rarity').append(option);}
$('applyBatch').onclick=()=>{const n=Number($('batchQty').value);if(!Number.isInteger(n)||n<0||n>99){$('status').textContent='批量份数必须为 0–99 的整数。';return;}const matched=filtered();matched.forEach(c=>quantities.set(c.id,n));render();$('deckNote').textContent=`已将 ${matched.length} 个匹配版本设为各 ${n} 份；其他选择保持不变。`;};
render();
$('printPreview').onclick=downloadPdf;
